export const items = [
    'add-event',
    'add-user',
    'arrow-narrow-left',
    'arrow-narrow-right',
    'bank-note',
    'bar-chart-square',
    'bell-01',
    'bell-02',
    'building',
    'check',
    'chevron',
    'clock-rewind',
    'copy',
    'cross',
    'cube',
    'dots-horizontal',
    'home',
    'line-chart-up',
    'link',
    'lock',
    'log-in',
    'log-out',
    'menu',
    'menu-2',
    'message',
    'pie-chart',
    'route',
    'search',
    'settings',
    'star',
    'unlock',
    'wallet',
    undefined
] as const;

export type IconToken = typeof items[number];
